app:
  jwtSecret: "jwt_secret"
  jwtExpirationMs: 600000
  dataLoader: true

server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: org.postgresql.Driver
    password: "password"
    url: "jdbc:postgresql://localhost:5432/journeymate"
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false