app:
  jwtSecret: "your-jwt-secret"
  jwtExpirationMs: 600000
  dataLoader: true

cloudinary:
  apiKey: "your-cloud-key"
  apiSecret: "your-cloud-secret"
  cloudName: "your-cloud-name"

server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: "password"
    url: "jdbc:postgresql://localhost:5432/journeymate"
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB